# Generated by Django 6.1.1 on 2026-09-27 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operations',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operations',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
