# Generated by Django 6.1.1 on 2026-09-27 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_operations_repeat_operations_shared_operations_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='type',
            field=models.CharField(choices=[('d', 'dépense'), ('r', 'revenus')], default='d', max_length=7),
        ),
    ]
